AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template ElastiCache: Sample template showing
  how to create an Amazon ElastiCache Cache Cluster with Auto Discovery and access
  it from a very simple PHP application. **WARNING** This template creates an Amazon
  Ec2 Instance and an Amazon ElastiCache Cluster. You will be billed for the AWS resources
  used if you create a stack from this template.'
Parameters:
  KeyName:
    Description: Name of an existing Amazon EC2 KeyPair for SSH access to the Web
      Server
    Type: String
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: m1.small
    AllowedValues: [t1.micro, m1.small, m1.medium, m1.large, m1.xlarge, m3.xlarge,
      m3.2xlarge, m2.xlarge, m2.2xlarge, m2.4xlarge, c1.medium, c1.xlarge, cc1.4xlarge,
      cc2.8xlarge, cg1.4xlarge, hi1.4xlarge, hs1.8xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  CacheNodeType:
    Default: cache.m1.small
    Description: The compute and memory capacity of the nodes in the Cache Cluster
    Type: String
    AllowedValues: [cache.m1.small, cache.m1.large, cache.m1.xlarge, cache.m2.xlarge,
      cache.m2.2xlarge, cache.m2.4xlarge, cache.c1.xlarge]
    ConstraintDescription: must select a valid Cache Node type.
  NumberOfCacheNodes:
    Default: '1'
    Description: The number of Cache Nodes the Cache Cluster should have
    Type: Number
    MinValue: '1'
    MaxValue: '10'
    ConstraintDescription: must be between 5 and 10.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: PV64
    m1.small:
      Arch: PV64
    m1.medium:
      Arch: PV64
    m1.large:
      Arch: PV64
    m1.xlarge:
      Arch: PV64
    m3.xlarge:
      Arch: PV64
    m3.2xlarge:
      Arch: PV64
    m2.xlarge:
      Arch: PV64
    m2.2xlarge:
      Arch: PV64
    m2.4xlarge:
      Arch: PV64
    c1.medium:
      Arch: PV64
    c1.xlarge:
      Arch: PV64
    cc1.4xlarge:
      Arch: CLU64
    cc2.8xlarge:
      Arch: CLU64
    cg1.4xlarge:
      Arch: GPU64
    hi1.4xlarge:
      Arch: PV64
    hs1.8xlarge:
      Arch: PV64
  AWSRegionArch2AMI:
    us-east-1:
      PV64: ami-1624987f
      CLU64: ami-08249861
      GPU64: ami-02f54a6b
    us-west-2:
      PV64: ami-2a31bf1a
      CLU64: ami-2431bf14
      GPU64: NOT_YET_SUPPORTED
    us-west-1:
      PV64: ami-1bf9de5e
      CLU64: NOT_YET_SUPPORTED
      GPU64: NOT_YET_SUPPORTED
    eu-west-1:
      PV64: ami-c37474b7
      CLU64: ami-d97474ad
      GPU64: ami-1b02026f
    ap-southeast-1:
      PV64: ami-a6a7e7f4
      CLU64: NOT_YET_SUPPORTED
      GPU64: NOT_YET_SUPPORTED
    ap-southeast-2:
      PV64: ami-bd990e87
      CLU64: NOT_YET_SUPPORTED
      GPU64: NOT_YET_SUPPORTED
    ap-northeast-1:
      PV64: ami-4e6cd34f
      CLU64: NOT_YET_SUPPORTED
      GPU64: NOT_YET_SUPPORTED
    sa-east-1:
      PV64: ami-1e08d103
      CLU64: NOT_YET_SUPPORTED
      GPU64: NOT_YET_SUPPORTED
Resources:
  CacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: !Ref 'CacheNodeType'
      CacheSecurityGroupNames: [!Ref 'CacheSecurityGroup']
      Engine: memcached
      NumCacheNodes: !Ref 'NumberOfCacheNodes'
  CacheSecurityGroup:
    Type: AWS::ElastiCache::SecurityGroup
    Properties:
      Description: Lock cache down to Web Server access only
  CacheSecurityGroupIngress:
    Type: AWS::ElastiCache::SecurityGroupIngress
    Properties:
      CacheSecurityGroupName: !Ref 'CacheSecurityGroup'
      EC2SecurityGroupName: !Ref 'WebServerSecurityGroup'
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref 'SSHLocation'
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
  WebServerHost:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
              gcc-c++: []
              php: []
              php-pear: []
          files:
            /var/www/html/index.php:
              content: !Join ['', ['<?php

                    ', 'echo ''<h1>AWS CloudFormation sample application for Amazon
                    ElastiCache</h1>'';

                    ', '

                    ', $server_endpoint = ', !GetAtt [CacheCluster, ConfigurationEndpoint.Address],
                  ''';

                    ', '$server_port = ', !GetAtt [CacheCluster, ConfigurationEndpoint.Port],
                  ';

                    ', '

                    ', '/**

                    ', ' * The following will initialize a Memcached client to utilize
                    the Auto Discovery feature.

                    ', " * \n", ' * By configuring the client with the Dynamic client
                    mode with single endpoint, the

                    ', ' * client will periodically use the configuration endpoint
                    to retrieve the current cache

                    ', ' * cluster configuration. This allows scaling the cache cluster
                    up or down in number of nodes

                    ', " * without requiring any changes to the PHP application. \n",
                  ' */

                    ', '

                    ', '$dynamic_client = new Memcached();

                    ', '$dynamic_client->setOption(Memcached::OPT_CLIENT_MODE, Memcached::DYNAMIC_CLIENT_MODE);

                    ', '$dynamic_client->addServer($server_endpoint, $server_port);

                    ', '

                    ', '$tmp_object = new stdClass;

                    ', '$tmp_object->str_attr = ''test'';

                    ', '$tmp_object->int_attr = 123;

                    ', '

                    ', '$dynamic_client->set(''key'', $tmp_object, 10) or die (''Failed
                    to save data to the cache'');

                    ', 'echo ''<p>Store data in the cache (data will expire in 10
                    seconds)</p>'';

                    ', '

                    ', '$get_result = $dynamic_client->get(''key'');

                    ', 'echo ''<p>Data from the cache:<br/>'';

                    ', '

                    ', 'var_dump($get_result);

                    ', '

                    ', 'echo ''</p>'';

                    ', '?>

                    ']]
              mode: '000644'
              owner: apache
              group: apache
          commands:
            00_install_memcached_client:
              command: pecl install https://s3.amazonaws.com/elasticache-downloads/ClusterClient/PHP/latest-64bit
            01_enable_auto_discovery:
              command: echo 'extension=amazon-elasticache-cluster-client.so' > /etc/php.d/memcached.ini
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
              sendmail:
                enabled: 'false'
                ensureRunning: 'false'
    Properties:
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch,
          !Ref 'InstanceType', Arch]]
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'WebServerSecurityGroup']
      KeyName: !Ref 'KeyName'
      UserData: !Base64
        Fn::Join:
        - ''
        - ['#!/bin/bash -v

            ', 'yum update -y aws-cfn-bootstrap

            ', '# Setup the PHP sample application

            ', '/opt/aws/bin/cfn-init ', '         --stack ', !Ref 'AWS::StackName',
          '         --resource WebServerHost ', '         --region ', !Ref 'AWS::Region',
          '

            ', '# Signal the status of cfn-init

            ', '/opt/aws/bin/cfn-signal -e $? ''', !Ref 'WebServerWaitHandle', '''

            ']
  WebServerWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  WebServerWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: WebServerHost
    Properties:
      Handle: !Ref 'WebServerWaitHandle'
      Timeout: '300'
Outputs:
  WebsiteURL:
    Value: !Join ['', ['http://', !GetAtt [WebServerHost, PublicDnsName]]]
    Description: Application URL
