AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template S3_With_CloudFront_Distribution:
  Sample template showing how to create a website with a custom DNS name, hosted on
  Amazon S3 and served via Amazone CloudFront. It assumes you already have a Hosted
  Zone registered with Amazon Route 53. **WARNING** This template creates an Amazon
  Route 53 DNS record, an S3 bucket and a CloudFront distribution. You will be billed
  for the AWS resources used if you create a stack from this template.'
Parameters:
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
Mappings:
  RegionMap:
    us-east-1:
      s3BucketDomain: .s3.amazonaws.com
    us-west-1:
      s3BucketDomain: .s3-us-west-1.amazonaws.com
    us-west-2:
      s3BucketDomain: .s3-us-west-2.amazonaws.com
    eu-west-1:
      s3BucketDomain: .s3-eu-west-1.amazonaws.com
    sa-east-1:
      s3BucketDomain: .s3-sa-east-1.amazonaws.com
    ap-northeast-1:
      s3BucketDomain: .s3-ap-northeast-1.amazonaws.com
    ap-southeast-1:
      s3BucketDomain: .s3-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      s3BucketDomain: .s3-ap-southeast-2.amazonaws.com
Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties: {}
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for S3-backed website
        CustomOrigin:
          DNSName: !Join ['', [!Ref 'S3BucketForWebsiteContent', !FindInMap [RegionMap,
                !Ref 'AWS::Region', s3BucketDomain]]]
          HTTPPort: '80'
          HTTPSPort: '443'
          OriginProtocolPolicy: http-only
        Enabled: 'true'
        DefaultRootObject: index.html
        CNAMEs:
        - !Join ['', [!Ref 'AWS::StackId', ., !Ref 'AWS::Region', ., !Ref 'HostedZone']]
  WebsiteDNSName:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join ['', [!Ref 'HostedZone', .]]
      Comment: CNAME redirect custom name to CloudFront distribution
      Name: !Join ['', [!Ref 'AWS::StackId', ., !Ref 'AWS::Region', ., !Ref 'HostedZone']]
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - !Join ['', ['http://', !GetAtt [WebsiteCDN, DomainName]]]
Outputs:
  WebsiteURL:
    Value: !Join ['', ['http://', !Ref 'WebsiteDNSName']]
    Description: The URL of the newly created website
  BucketName:
    Value: !Ref 'S3BucketForWebsiteContent'
    Description: Name of S3 bucket to hold website content
